### PR TITLE
Update http.jl

### PR DESCRIPTION
**Pull request by rathod-b**
`empty!()` the JuMP models post solve before `GC.gc()`

### Please check if the PR fulfills these requirements
- [ ] CHANGELOG.md is updated
- [X] Tests for the changes have been added (for bug fixes / features) (see other information)
- [X] Docs have been added / updated (for bug fixes / features) (see other information)

### What kind of change does this PR introduce?
(Bug fix, feature, docs update, ...)
Memory management feature for JuMP models

### What is the current behavior?
(You can also link to an open issue here)
Post solve, JuMP models are finalized and handled before garbage collection. However, upon initial testing this does not reduce the size of JuMP models (might even increase the size in some cases).

### What is the new behavior (if this is a feature change)?
Now, the JuMP models will be `empty!()` before the `GC.gc()` is called which should free up memory held by these models post solve

### Does this PR introduce a breaking change?
(What changes might users need to make in their application due to this PR?)
No

### Other information:
If all inbuilt API tests pass, testing for this PR will have to be via Rancher. We would have to monitor resource consumption there and see if there is a reduction in how often the infrastructure is out of memory. See Issue #417 for more details on tests done using VM.
No user facing docs need to be updated.

### CODE REVIEW

**Review by Bill-Becker — APPROVED** [review]

**Comment by rathod-b** [comment]
Commented out some Julia pod memory management safeguards implemented by Nick M. for testing purposes.

**Comment by Bill-Becker** [comment]
@rathod-b I'm curious to see if this helps our current issues with calling /dev on production right now. It's super slow, and it looks like /dev (REopt.jl with 2-threads) is causing a quicker buildup of memory on the pods/containers. I don't see how this could hurt, so I'd like to merge this in soon (by mid-day Monday to test).

I noticed you removed the memory limit setting for the Julia pods - do we think that is necessary and safe, or did you do this just to test?

**Comment by Bill-Becker** [comment]
Hosting the API locally, I did a pretty manual tracking of memory in the julia container as I ran several runs, before and after these additions with empty! - I'm still seeing the same kind of memory growth. Whenever http.jl (and therefore Julia) is restarted, the memory consumption reduces back down to small, but then I do runs and it creeps back up. Was the improvement you saw pretty conclusive? Let's chat early next week.

**Comment by rathod-b** [comment]
> Hosting the API locally, I did a pretty manual tracking of memory in the julia container as I ran several runs, before and after these additions with empty! - I'm still seeing the same kind of memory growth. Whenever http.jl (and therefore Julia) is restarted, the memory consumption reduces back down to small, but then I do runs and it creeps back up. Was the improvement you saw pretty conclusive? Let's chat early next week.

I believe the improvement I saw after adding empty!() was quite conclusive because prior to that change, REopt.jl would have maxed out the VM memory in ~2k runs. After the change it didnt max out the memory. It got relatively close to using 70% of RAM on the VM and stayed near that number for the runtime of about 2 days (with interruptions in the VM).

Maybe we should explore what it would look like to host REopt.jl on a dedicated HPC node? everyone is moving on to the new Kestrel system so there is reduced load on Eagle now.

**Comment by Bill-Becker** [comment]
Ok, yeah I was seeing the memory would grow from less than 1GB to up to 4.5-5GB in less than 10 runs, and then it did seem to stop growing as much. Sometimes it would reduce by a little, then grow a little more. I didn't do nearly as exhaustive testing as you did, but there was a clear trend of growth that wouldn't reduce. Do you understand why it grows initially and then seems to level off, as it did in your case and mine?

**Comment by rathod-b** [comment]
> Ok, yeah I was seeing the memory would grow from less than 1GB to up to 4.5-5GB in less than 10 runs, and then it did seem to stop growing as much. Sometimes it would reduce by a little, then grow a little more. I didn't do nearly as exhaustive testing as you did, but there was a clear trend of growth that wouldn't reduce. Do you understand why it grows initially and then seems to level off, as it did in your case and mine?

Unsure as to why memory would grow initially. It could be Julia and Xpress expanding memory consumption for problem solving, and then eventually they find a steady state condition where memory becomes a limiting factor for all the workers?

**Comment by Bill-Becker** [comment]
@rathod-b any reason not to merge this into develop first instead of master? And I think this is good to go, right?

**Comment by Bill-Becker** [comment]
This was merged into develop already, so maybe we can close this?

**Comment by rathod-b** [comment]
> This was merged into develop already, so maybe we can close this?

Yes, we sure can! Apologies for the delayed responses on this.

**Pull request closed without merging**
