### PR TITLE
Add AbsorptionChiller models, absorption_chiller_defaults/ endpoint to job/ app

### PR DESCRIPTION
**Pull request by zolanaj**
### Please check if the PR fulfills these requirements
- [x] CHANGELOG.md is updated
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce?
- Adds AbsorptionChillerInputs and AbsorptionChillerOutputs models to job/ app
- Adds `absorption_chiller_defaults` endpoint which calls the http.jl absorption_chiller_defaults endpoint

### CODE REVIEW

**Comment by zolanaj** [comment]
@Bill-Becker this has a lot of parallels to https://github.com/NREL/REopt_API/pull/382 in which you added the CHP endpoint, in case that helps your review.

**Review by Bill-Becker — CHANGES_REQUESTED** [review]
This is fully on the REopt.jl side, but I didn't catch it in that review: it's a little strange that `thermal_consumption_hot_water_or_steam` comes back twice in the response of the `get_absoprtion_chiller_defaults` function in REopt.jl which is then passed back in this API endpoint. They are always the same value. I'd say we just want the one in the outer dictionary instead of in the `default_inputs` because it's a processed/calculated value if it's not provided.
{
    "default_inputs": {
        "installed_cost_per_ton": 1547.0,
        "cop_thermal": 1.42,
        "thermal_consumption_hot_water_or_steam": "steam",
        "om_cost_per_ton": 28.0
    },
    "thermal_consumption_hot_water_or_steam": "steam"
}

**Comment by zolanaj** [comment]
@Bill-Becker this has been updated, but when updating the version of REopt, it includes passing of warnings and error messages through Julia, which is leading to a failure of the 400-code error test here: https://github.com/NREL/REopt_API/blob/f6ef02e4e11a6216b6366989ec12c0a773123ac0/job/test/test_job_endpoint.py#L121-L138

I think I can edit the test but want to make sure there's nothing else I'm missing.  Or should I just bump the REopt.jl version in a separate PR?

**Comment by Bill-Becker** [comment]
@zolanaj I know we talked about this in the meeting, but seems like a good idea to just have Bhavesh make the update in https://github.com/NREL/REopt_API/pull/429, and then we can wait until that is merged to merge develop into this branch to resolve. Would that work?

**Comment by zolanaj** [comment]
I'm still dealing with the failed test after the merge, so I'll work on a separate PR that bumps the REopt.jl version to 0.26.0 and see if I can get things working that way.

**Comment by zolanaj** [comment]
@Bill-Becker after updating migrations and fully catching up to develop, this is ready for your review again!

**Review by Bill-Becker — APPROVED** [review]
Thanks @zolanaj. I tested the endpoint and it looks good!

**Pull request merged**
